# Generated by Django 4.2.23 on 2025-07-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=125)),
                ('Description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Upload product image', null=True, upload_to='products/')),
                ('category', models.CharField(max_length=125)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
